apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-pod
  labels:
    project: kubernetes-project
spec:
  containers:
  - name: pod
    image: aminou12345/flask-app:latest
    ports:
    - containerPort: 31111