apiVersion: v1
kind: Service
metadata:
  name: kubernetes-svc
spec:
  selector:
    project: kubernetes-project
  type: NodePort
  ports:
    - protocol: TCP
      port: 31111 
      targetPort: 5000
      nodePort: 31111
